WITH first_time_loaders_post AS (
  SELECT DISTINCT USER_ID
  FROM PROD_DB.PUBLIC.CLEVERTAP_CUSTOMER
  WHERE EVENT_NAME = 'booking_homepage_loaded'
    AND TIMESTAMP >= '2026-03-28' AND TIMESTAMP < '2026-04-13'
    AND TRY_CAST(TRY_PARSE_JSON(PROPERTIES):"profile.events.booking_homepage_loaded.count"::STRING AS INT) = 1
)
SELECT
  e.EVENT_NAME,
  COUNT(DISTINCT b.USER_ID) AS distinct_users
FROM first_time_loaders_post b
JOIN PROD_DB.PUBLIC.CLEVERTAP_CUSTOMER e ON e.USER_ID = b.USER_ID
WHERE e.TIMESTAMP >= '2026-03-28' AND e.TIMESTAMP < '2026-04-13'
GROUP BY 1
ORDER BY 2 DESC
LIMIT 30
