// Auto-generated by refresh_dashboard.py
const DASHBOARD_DATA = {
  "refreshed_at": "2026-04-22 11:34",
  "post_funnel": {
    "total": 850,
    "ssid": 819,
    "address": 810,
    "verified": 741,
    "notif": 735,
    "interested": 630,
    "slot": 616,
    "confirmed": 609,
    "assigned": 561,
    "otp": 319,
    "cancelled": 561
  },
  "post_churn": {
    "s8_cust": 40,
    "s8_sys": 14,
    "s9_cust": 129,
    "s9_sys": 122,
    "s9_pred": 198,
    "s9_entry": 557
  },
  "new_release": {
    "installs": 4576,
    "homepage": 4482,
    "check": 3699,
    "serviceable": 2203,
    "unserviceable": 74,
    "how_works": 2113,
    "get_started": 1697,
    "cost": 1619,
    "pay100": 1081,
    "location": 0,
    "paid": 203
  },
  "variants": {
    "A": {
      "entry": 809,
      "cost": 779,
      "pay100": 544,
      "location": 0,
      "paid": 107
    },
    "B": {
      "entry": 305,
      "cost": 293,
      "pay100": 208,
      "location": 0,
      "paid": 38
    },
    "C": {
      "entry": 274,
      "cost": 252,
      "pay100": 173,
      "location": 0,
      "paid": 29
    },
    "D": {
      "entry": 275,
      "cost": 264,
      "pay100": 142,
      "location": 0,
      "paid": 25
    }
  }
};
